# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.5.3
      - image: redis:2.8.19

    working_directory: ~/my-project
    
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
          
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            mkdir test-reports/
            cd tests && python tests.py
            cp reports/*.xml ../test-reports
            

      - run:
          name: run coverage
          command: |
            . venv/bin/activate
            cd tests && coverage run tests.py

      - run:
          name: upload coverage to codacy
          command: |
            . venv/bin/activate
            cd tests && coverage xml && python-codacy-coverage -r coverage.xml

      - store_artifacts:
          path: test-reports/
          destination: tr1

      - store_test_results:
          path: test-reports/   
