version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.5.3
      - image: redis:2.8.19

    working_directory: ~/my-project

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
          
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            mkdir test-reports/
            cd tests && python tests.py
            cp reports/*.xml ../test-reports
            rm -rf reports/*.xml

      - run:
          name: run integration tests
          command: |
            . venv/bin/activate
            cd tests && python integrationtests.py
            cp reports/*.xml ../test-reports

      - run:
          name: run coverage
          command: |
            . venv/bin/activate
            cd tests && coverage run tests.py

      - run:
          name: upload coverage to codacy
          command: |
            . venv/bin/activate
            cd tests && coverage xml && python-codacy-coverage -r coverage.xml

      - store_artifacts:
          path: test-reports/
          destination: tr1

      - store_test_results:
          path: test-reports/


  deploy-pypi:
    docker:
      - image: circleci/python:3.5.3

    working_directory: ~/my-project

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Deploy to PyPi
          command: |
            . venv/bin/activate
            setup.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy-pypi:
          requires:
            - build
          filters:
            branches:
              only: release

